-- AlterTable
ALTER TABLE "Impresso" ADD COLUMN     "gramas100" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pesoRoloG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "precoRolo" DOUBLE PRECISION NOT NULL DEFAULT 0;
